name: Convert Jupyter README

on:
  push:
    branches:
    - main

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies & Convert README.ipynb
      run: |
        python -m pip install --upgrade pip
        python -m pip install nbconvert
        jupyter nbconvert --to markdown CandyCare.ipynb
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add CandyCare.md
        git rm README.md
        git mv CandyCare.md README.md
        git commit -m "Convert CandyCare.ipynb to README.md" -a
        
    - name: Push changes
      if: success()
      uses: ad-m/github-push-action@master
      with:
        branch: main
        github_token: ${{ secrets.ACCESS_TOKEN }}
